(function () {
  "use strict";
  var supabaseClient = window.grupoSurSupabaseClient;
  var state = { userId: "", cases: [], events: {}, applications: {}, notifications: [], leads: [], quotes: [], models: [], campaigns: [], credits: [], activeCase: null, activeQuote: null };
  var quoteDialog = document.getElementById("quoteDialog");
  var quoteForm = document.getElementById("quoteForm");
  var minuteDialog = document.getElementById("salesMinuteDialog");
  var minuteForm = document.getElementById("salesMinuteForm");

  function escapeHtml(value) { return String(value == null ? "" : value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;"); }
  function money(value) { return value == null || value === "" ? "A confirmar" : "$" + new Intl.NumberFormat("es-AR", { maximumFractionDigits: 0 }).format(Number(value)); }
  function formatDate(value) { return value ? new Intl.DateTimeFormat("es-AR", { day: "2-digit", month: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(new Date(value)) : "—"; }
  function outcome(value) { return ({ pending: "Pendiente", approved: "Aprobado", observed: "Observado", rejected: "Rechazado", baja: "Baja", cancelled: "Baja" })[value] || value; }
  function statusLabel(value) { return ({ minute_pending: "Minuta pendiente", quality_control: "Control de calidad", dealer_scoring: "Scoring concesionario", contract_signature: "Firma de contrato", formation_group: "Finalizada · formación de grupo", grouped: "Finalizada · agrupado", finalized: "Finalizada" })[value] || value; }
  function setBusy(button, busy, label) { if (busy) { button.dataset.label = button.textContent; button.textContent = label; button.disabled = true; } else { button.textContent = button.dataset.label || button.textContent; button.disabled = false; } }
  function latestApplication(caseId) { return (state.applications[caseId] || []).slice().sort(function (a, b) { return Number(b.revision_number) - Number(a.revision_number); })[0] || null; }
  function selectedModel() { return state.models.find(function (item) { return item.id === quoteForm.elements.modelId.value; }); }
  function selectedOffer() { var list = quoteForm.elements.offerType.value === "bank_credit" ? state.credits : state.campaigns; return list.find(function (item) { return item.id === quoteForm.elements.offerId.value; }); }
  function offerName(item, type) { return type === "bank_credit" ? item.financier_name + " · " + item.offer_name + " · " + item.term_months + " cuotas" : item.plan_name + (item.version_name ? " · " + item.version_name : "") + (item.installment_count ? " · " + item.installment_count + " cuotas" : ""); }
  function isCurrentlyValid(item) { var today = new Date().toISOString().slice(0, 10); return item.active !== false && (!item.valid_from || item.valid_from <= today) && (!item.valid_to || item.valid_to >= today); }
  function quoteCode() { return "GS-PRES-" + Date.now().toString(36).toUpperCase() + "-" + Math.random().toString(36).slice(2, 6).toUpperCase(); }

  async function ensureUser() { if (state.userId) return state.userId; var auth = await supabaseClient.auth.getUser(); state.userId = auth.data && auth.data.user ? auth.data.user.id : ""; return state.userId; }

  async function loadCatalog() {
    var results = await Promise.all([
      supabaseClient.from("models").select("id, name, active, brand:brands!inner(name)").eq("active", true).order("sort_order"),
      supabaseClient.from("campaigns").select("id, model_id, plan_name, version_name, transmission, installment_count, advance_amount, installment_amount, installment_is_from, active, valid_from, valid_to, bonus, benefits").eq("active", true).order("sort_order"),
      supabaseClient.from("bank_credit_offers").select("id, model_id, financier_name, offer_name, term_months, min_financed_amount, max_financed_amount, installment_coefficient, breakage_rate, patenting_rate, fixed_expenses, tna, cftea, notes, active, valid_from, valid_to, versions:bank_credit_offer_versions(version:model_versions(id,name))").eq("active", true).order("sort_order")
    ]);
    state.models = results[0].data || []; state.campaigns = results[1].data || []; state.credits = results[2].data || [];
  }

  async function loadQuotes() {
    await ensureUser(); await loadCatalog();
    var results = await Promise.all([
      supabaseClient.from("leads").select("id, customer_name, customer_phone, model_interest, created_at").eq("assigned_seller_user_id", state.userId).order("created_at", { ascending: false }).limit(500),
      supabaseClient.from("sales_quotes").select("id, quote_code, lead_id, model_id, offer_type, customer_name, vehicle_version, sale_price, financed_amount, installment_amount, advance_amount, breakage_amount, patenting_amount, expenses_amount, final_advance_amount, status, issued_at, valid_until, commercial_snapshot").eq("seller_user_id", state.userId).order("issued_at", { ascending: false }).limit(500)
    ]);
    state.leads = results[0].data || []; state.quotes = results[1].data || []; renderQuotes();
  }

  function renderQuotes() {
    document.getElementById("quotesList").innerHTML = state.quotes.length ? state.quotes.map(function (item) {
      var snapshot = item.commercial_snapshot || {};
      return '<article class="quote-history-card" data-quote-id="' + item.id + '"><div><strong>' + escapeHtml(item.quote_code) + '</strong><span>' + escapeHtml(item.customer_name + " · " + (snapshot.brand || "") + " " + (snapshot.model || "") + " " + item.vehicle_version) + '</span><small>' + escapeHtml(formatDate(item.issued_at)) + ' · vigente hasta ' + escapeHtml(formatDate(item.valid_until)) + '</small></div><div><strong>' + escapeHtml(money(item.final_advance_amount)) + ' anticipo final</strong><span>' + escapeHtml(money(item.installment_amount)) + ' por cuota · ' + escapeHtml(item.offer_type === "bank_credit" ? "Crédito de terminal" : "Plan de ahorro") + '</span></div><button class="primary-button compact-button" data-print-quote type="button">Imprimir</button></article>';
    }).join("") : '<div class="agenda-empty">Todavía no generaste presupuestos asociados a tus Leads.</div>';
  }

  function populateModels(modelHint) {
    document.getElementById("quoteModel").innerHTML = '<option value="">Seleccionar modelo</option>' + state.models.map(function (item) { var brand = Array.isArray(item.brand) ? item.brand[0] : item.brand; return '<option value="' + item.id + '">' + escapeHtml((brand && brand.name || "") + " · " + item.name) + '</option>'; }).join("");
    if (modelHint) { var match = state.models.find(function (item) { return String(modelHint).toLowerCase().includes(item.name.toLowerCase()); }); if (match) document.getElementById("quoteModel").value = match.id; }
  }
  function populateOffers() {
    var modelId = quoteForm.elements.modelId.value; var type = quoteForm.elements.offerType.value; var list = (type === "bank_credit" ? state.credits : state.campaigns).filter(function (item) { return item.model_id === modelId && isCurrentlyValid(item); });
    document.getElementById("quoteOffer").innerHTML = list.length ? list.map(function (item) { return '<option value="' + item.id + '">' + escapeHtml(offerName(item, type)) + '</option>'; }).join("") : '<option value="">No hay condiciones cargadas para este modelo</option>';
    document.querySelectorAll("[data-bank-field]").forEach(function (field) { field.hidden = type !== "bank_credit"; });
    var offer = selectedOffer(); var versions = [];
    if (offer && type === "bank_credit") versions = (offer.versions || []).map(function (link) { return Array.isArray(link.version) ? link.version[0] : link.version; }).filter(Boolean).map(function (version) { return version.name; });
    if (offer && type === "savings_plan") versions = [[offer.version_name, offer.transmission].filter(Boolean).join(" ") || "Versión a confirmar"];
    document.getElementById("quoteVersion").innerHTML = versions.length ? versions.map(function (version) { return '<option value="' + escapeHtml(version) + '">' + escapeHtml(version) + '</option>'; }).join("") : '<option value="">No hay versiones habilitadas</option>';
    if (offer && type === "savings_plan") quoteForm.elements.financedAmount.value = "";
    calculateQuote();
  }
  function quoteValues() {
    var type = quoteForm.elements.offerType.value; var offer = selectedOffer(); var price = Number(quoteForm.elements.salePrice.value || 0); if (!offer || !price) return null;
    if (type === "bank_credit") {
      var financed = Number(quoteForm.elements.financedAmount.value || 0); var advance = Math.max(0, price - financed); var breakage = financed * Number(offer.breakage_rate || 0) / 100; var patenting = price * Number(offer.patenting_rate || 0) / 100; var expenses = Number(offer.fixed_expenses || 0);
      return { price: price, financed: financed, advance: advance, breakage: breakage, patenting: patenting, expenses: expenses, finalAdvance: advance + breakage + patenting + expenses, installment: financed * Number(offer.installment_coefficient), term: offer.term_months };
    }
    var planAdvance = Number(offer.advance_amount || 0); return { price: price, financed: Math.max(0, price - planAdvance), advance: planAdvance, breakage: 0, patenting: 0, expenses: 0, finalAdvance: planAdvance, installment: Number(offer.installment_amount || 0), term: offer.installment_count };
  }
  function calculateQuote() { var values = quoteValues(); document.getElementById("quoteCalculation").innerHTML = values ? [["Anticipo", values.advance], ["Quebranto", values.breakage], ["Patentamiento", values.patenting], ["Gastos", values.expenses], ["Anticipo final", values.finalAdvance], ["Cuota", values.installment]].map(function (row) { return '<div><span>' + row[0] + '</span><strong>' + escapeHtml(money(row[1])) + '</strong></div>'; }).join("") : '<div><span>Completá precio y condición</span><strong>—</strong></div>'; }

  async function openQuote(leadId) {
    await loadQuotes(); quoteForm.reset(); document.getElementById("quoteError").textContent = "";
    document.getElementById("quoteLead").innerHTML = state.leads.length ? state.leads.map(function (lead) { return '<option value="' + lead.id + '">' + escapeHtml((lead.customer_name || "Cliente sin nombre") + " · +" + lead.customer_phone) + '</option>'; }).join("") : '<option value="">No hay Leads disponibles</option>';
    if (leadId) document.getElementById("quoteLead").value = leadId; var lead = state.leads.find(function (item) { return item.id === document.getElementById("quoteLead").value; }); populateModels(lead && lead.model_interest); document.getElementById("quoteOfferType").value = "savings_plan"; var limit = new Date(); limit.setDate(limit.getDate() + 7); quoteForm.elements.validUntil.value = limit.toISOString().slice(0, 10); populateOffers(); quoteDialog.showModal();
  }

  function quoteSnapshot(item) { var model = state.models.find(function (row) { return row.id === item.model_id; }); var brand = model && (Array.isArray(model.brand) ? model.brand[0] : model.brand); return { brand: brand && brand.name || "", model: model && model.name || "", offer_name: item.offer_name || item.plan_name || "", financier: item.financier_name || "", tna: item.tna || null, cftea: item.cftea || null, coefficient: item.installment_coefficient || null, breakage_rate: item.breakage_rate || 0, patenting_rate: item.patenting_rate || 0, benefits: item.benefits || [], bonus: item.bonus || "" }; }
  async function saveQuote(event) {
    event.preventDefault(); var button = document.getElementById("quoteSubmit"); var errorBox = document.getElementById("quoteError"); errorBox.textContent = ""; var values = quoteValues(); var offer = selectedOffer(); var lead = state.leads.find(function (item) { return item.id === quoteForm.elements.leadId.value; });
    if (!lead || !offer || !values || values.price <= 0) { errorBox.textContent = "Completá el Lead, modelo, condición y precio de venta."; return; }
    if (quoteForm.elements.offerType.value === "bank_credit" && (values.financed <= 0 || values.financed > values.price)) { errorBox.textContent = "El monto financiado debe ser mayor a cero y no superar el precio."; return; }
    if ((offer.min_financed_amount && values.financed < Number(offer.min_financed_amount)) || (offer.max_financed_amount && values.financed > Number(offer.max_financed_amount))) { errorBox.textContent = "El monto financiado está fuera del rango habilitado para esta línea."; return; }
    setBusy(button, true, "Guardando…"); var code = quoteCode(); var type = quoteForm.elements.offerType.value; var snapshot = quoteSnapshot(offer);
    var insert = await supabaseClient.from("sales_quotes").insert({ quote_code: code, lead_id: lead.id, seller_user_id: state.userId, model_id: quoteForm.elements.modelId.value, campaign_id: type === "savings_plan" ? offer.id : null, bank_credit_offer_id: type === "bank_credit" ? offer.id : null, offer_type: type, customer_name: lead.customer_name || "Cliente sin nombre", vehicle_version: quoteForm.elements.vehicleVersion.value.trim(), sale_price: values.price, financed_amount: values.financed, term_months: values.term, installment_amount: values.installment, advance_amount: values.advance, breakage_amount: values.breakage, patenting_amount: values.patenting, expenses_amount: values.expenses, final_advance_amount: values.finalAdvance, valid_until: quoteForm.elements.validUntil.value + "T23:59:59-03:00", commercial_snapshot: snapshot }).select("*").single();
    if (insert.error) { errorBox.textContent = insert.error.message; setBusy(button, false); return; }
    state.activeQuote = insert.data; quoteDialog.close(); await loadQuotes(); printQuote(insert.data); setBusy(button, false);
  }

  function printQuote(item) {
    var snapshot = item.commercial_snapshot || {}; var rows = [["Cliente", item.customer_name], ["Vehículo", [snapshot.brand, snapshot.model, item.vehicle_version].filter(Boolean).join(" ")], ["Condición", snapshot.financier ? snapshot.financier + " · " + snapshot.offer_name : snapshot.offer_name], ["Precio de venta", money(item.sale_price)], ["Monto financiado", money(item.financed_amount)], ["Anticipo", money(item.advance_amount)], ["Quebranto", money(item.breakage_amount)], ["Patentamiento", money(item.patenting_amount)], ["Gastos", money(item.expenses_amount)], ["Anticipo final", money(item.final_advance_amount)], ["Cantidad de cuotas", item.term_months], ["Valor de cuota", money(item.installment_amount)], ["TNA", snapshot.tna == null ? "No informada" : snapshot.tna + "%"], ["CFTEA", snapshot.cftea == null ? "No informado" : snapshot.cftea + "%"]];
    document.getElementById("minutePrint").innerHTML = '<article class="minute-sheet"><header class="minute-header"><div class="minute-header-brand"><img class="minute-company-logo" src="../assets/logo-header.webp" alt="Grupo Sur Automotores"></div><div class="minute-identifiers"><strong>' + escapeHtml(item.quote_code) + '</strong><span>Fecha: ' + escapeHtml(formatDate(item.issued_at)) + '</span></div></header><section class="minute-print-section"><h2>Presupuesto comercial</h2><div class="minute-data-grid three-columns">' + rows.map(function (row) { return '<div><span>' + escapeHtml(row[0]) + '</span><strong>' + escapeHtml(String(row[1] == null ? "—" : row[1])) + '</strong></div>'; }).join("") + '</div></section><section class="minute-print-section"><h2>Condiciones</h2><p>Propuesta informativa sujeta a vigencia, disponibilidad, aprobación crediticia y condiciones definitivas de la terminal o concesionario. Vigencia: ' + escapeHtml(formatDate(item.valid_until)) + '.</p></section><div class="minute-signatures"><div>Firma del cliente</div><div>Aclaración y DNI</div><div>Asesor responsable</div></div><footer class="minute-footer">Documento emitido desde el portal interno de Grupo Sur Automotores</footer></article>';
    document.getElementById("minutePrint").setAttribute("aria-hidden", "false"); document.body.classList.add("printing-minute"); window.print();
  }

  async function loadSales() {
    await ensureUser(); var results = await Promise.all([
      supabaseClient.from("sales_cases").select("id, case_code, vehicle, sale_amount, status, cdn_scoring_status, dealer_scoring_status, contract_status, finalized_at, created_at, updated_at").eq("seller_user_id", state.userId).order("updated_at", { ascending: false }),
      supabaseClient.from("commercial_applications").select("id, sales_case_id, revision_number, status, created_at").eq("seller_user_id", state.userId).not("sales_case_id", "is", null).order("revision_number", { ascending: false }),
      supabaseClient.from("sales_case_events").select("id, sales_case_id, stage, outcome, comment, created_at").order("created_at", { ascending: false }).limit(500),
      supabaseClient.from("sales_notifications").select("id, sales_case_id, notification_type, title, body, read_at, created_at").eq("recipient_user_id", state.userId).order("created_at", { ascending: false }).limit(100)
    ]);
    state.cases = results[0].data || []; state.applications = {}; (results[1].data || []).forEach(function (item) { (state.applications[item.sales_case_id] || (state.applications[item.sales_case_id] = [])).push(item); }); state.events = {}; (results[2].data || []).forEach(function (item) { (state.events[item.sales_case_id] || (state.events[item.sales_case_id] = [])).push(item); }); state.notifications = results[3].data || []; renderSales();
  }
  function processChip(label, value) { return '<span class="' + escapeHtml(value) + '">' + escapeHtml(label + " · " + outcome(value)) + '</span>'; }
  function renderSales() {
    var unread = state.notifications.filter(function (item) { return !item.read_at; }).length; var badge = document.getElementById("salesNotificationCount"); badge.textContent = unread; badge.hidden = unread === 0;
    document.getElementById("salesNotifications").innerHTML = state.notifications.filter(function (item) { return !item.read_at; }).map(function (item) { return '<article class="seller-notification ' + (item.notification_type === "cancelled" ? "cancelled" : "") + '" data-notification-id="' + item.id + '"><div><strong>' + escapeHtml(item.title) + '</strong><span> · ' + escapeHtml(item.body) + '</span></div><button data-read-notification type="button">×</button></article>'; }).join("");
    document.getElementById("salesTrackingList").innerHTML = state.cases.length ? state.cases.map(function (item) { var application = latestApplication(item.id); var observations = (state.events[item.id] || []).filter(function (event) { return event.outcome === "observed" && event.comment; }); var canMinute = item.status === "minute_pending" || item.cdn_scoring_status === "observed"; return '<article class="sales-tracking-card" data-sales-case-id="' + item.id + '"><div class="sales-tracking-head"><div><h3>' + escapeHtml(item.case_code + " · " + item.vehicle) + '</h3><p>' + escapeHtml(statusLabel(item.status)) + ' · actualizada ' + escapeHtml(formatDate(item.updated_at)) + '</p></div><span class="crm-stage">' + escapeHtml(item.finalized_at ? "Finalizada" : statusLabel(item.status)) + '</span></div><div class="sales-process">' + processChip("CDN", item.cdn_scoring_status) + processChip("Concesionario", item.dealer_scoring_status) + processChip("Contrato", item.contract_status) + '</div>' + observations.map(function (event) { return '<div class="seller-notification"><strong>Observación:</strong><span>' + escapeHtml(event.comment) + '</span></div>'; }).join("") + '<div class="sales-card-actions"><small>' + (application ? "Minuta enviada · versión " + application.revision_number : "La minuta todavía no fue enviada") + '</small>' + (canMinute ? '<button class="primary-button compact-button" data-open-minute type="button">' + (application ? "Corregir minuta" : "Completar minuta") + '</button>' : '') + '</div></article>'; }).join("") : '<div class="agenda-empty">Todavía no tenés ventas en proceso administrativo.</div>';
  }

  function deriveMinuteCommercial(salesCase) { var brand = ["Volkswagen", "Peugeot", "Fiat"].find(function (name) { return salesCase.vehicle.toLowerCase().includes(name.toLowerCase()); }) || "A confirmar"; return { brand: brand, model: salesCase.vehicle, campaign: "Venta aprobada por supervisión" }; }
  function openMinute(caseId) { state.activeCase = state.cases.find(function (item) { return item.id === caseId; }); if (!state.activeCase) return; var commercial = deriveMinuteCommercial(state.activeCase); minuteForm.reset(); minuteForm.elements.installmentsPaid.value = 0; minuteForm.elements.agreedPrice.value = state.activeCase.sale_amount || ""; document.getElementById("salesMinuteTitle").textContent = (latestApplication(caseId) ? "Corregir minuta · " : "Completar minuta · ") + state.activeCase.case_code; document.getElementById("salesMinuteVehicle").textContent = commercial.model; document.getElementById("salesMinuteCampaign").textContent = commercial.campaign; document.getElementById("salesMinuteError").textContent = ""; minuteDialog.showModal(); }
  async function saveMinute(event) {
    event.preventDefault(); var f = minuteForm.elements; var errorBox = document.getElementById("salesMinuteError"); var button = document.getElementById("salesMinuteSubmit"); errorBox.textContent = ""; var digits = function (value) { return String(value || "").replace(/\D/g, ""); }; var documentNumber = digits(f.documentNumber.value); var cuil = digits(f.cuil.value); if (documentNumber.length < 7 || cuil.length !== 11) { errorBox.textContent = "Revisá el DNI y el CUIL. El CUIL debe tener 11 dígitos."; return; } if (!f.applicationConsent.checked) { errorBox.textContent = "Confirmá la lectura conjunta de la minuta."; return; }
    var firstDate = f.firstPaymentDate.value || null, firstAmount = f.firstPaymentAmount.value || null, secondDate = f.secondPaymentDate.value || null, secondAmount = f.secondPaymentAmount.value || null; if (!!firstDate !== !!firstAmount || !!secondDate !== !!secondAmount) { errorBox.textContent = "Cada fecha de pago debe tener su importe correspondiente."; return; }
    var revision = Math.max(0, ...(state.applications[state.activeCase.id] || []).map(function (item) { return Number(item.revision_number); })) + 1; var commercial = deriveMinuteCommercial(state.activeCase); setBusy(button, true, "Guardando…");
    var payload = { prequalification_event_id: null, sales_case_id: state.activeCase.id, revision_number: revision, seller_user_id: state.userId, request_code: state.activeCase.case_code + "-R" + revision, brand_name: commercial.brand, model_name: commercial.model, campaign_name: f.planType.value.trim() || commercial.campaign, first_name: f.firstName.value.trim(), last_name: f.lastName.value.trim(), document_type: f.documentType.value, document_number: documentNumber, cuil: cuil, birth_date: f.birthDate.value, address: f.address.value.trim(), city_province: f.cityProvince.value.trim(), postal_code: f.postalCode.value.trim(), marital_status: f.maritalStatus.value, spouse_name: f.spouseName.value.trim() || null, spouse_document: digits(f.spouseDocument.value) || null, primary_phone: f.primaryPhone.value.trim(), alternate_phone: f.alternatePhone.value.trim() || null, email: f.email.value.trim().toLowerCase(), contact_schedule: f.contactSchedule.value.trim(), employment_status: f.employmentStatus.value, employer_name: f.employerName.value.trim(), employment_seniority: String(f.employmentSeniority.value), monthly_income: Number(f.monthlyIncome.value), automatic_debit: f.automaticDebit.value === "true", deferred_installment: f.deferredInstallment.value === "true", installments_paid: Number(f.installmentsPaid.value), installments_to_pay: Number(f.installmentsToPay.value), plan_type: f.planType.value.trim(), agreed_price: Number(f.agreedPrice.value), first_payment_date: firstDate, first_payment_amount: firstAmount ? Number(firstAmount) : null, second_payment_date: secondDate, second_payment_amount: secondAmount ? Number(secondAmount) : null, status: "submitted", terms_version: "GS-MINUTA-2026-01", confirmed_at: new Date().toISOString(), submitted_at: new Date().toISOString(), commercial_snapshot: { source: "crm_sale", case_code: state.activeCase.case_code, vehicle: state.activeCase.vehicle, sale_amount: state.activeCase.sale_amount } };
    var result = await supabaseClient.from("commercial_applications").insert(payload).select("id").single(); if (result.error) { errorBox.textContent = result.error.message; setBusy(button, false); return; } minuteDialog.close(); await loadSales(); printSalesMinute(payload); setBusy(button, false);
  }
  function minuteRow(label, value) { return '<div><span>' + escapeHtml(label) + '</span><strong>' + escapeHtml(String(value == null || value === "" ? "—" : value)) + '</strong></div>'; }
  function printSalesMinute(data) { document.getElementById("minutePrint").innerHTML = '<article class="minute-sheet"><header class="minute-header"><div class="minute-header-brand"><img class="minute-company-logo" src="../assets/logo-header.webp" alt="Grupo Sur Automotores"><span>Minuta de venta</span></div><div class="minute-identifiers"><strong>' + escapeHtml(data.request_code) + '</strong><span>' + escapeHtml(formatDate(data.submitted_at)) + '</span></div></header><section class="minute-print-section"><h2>Datos del cliente</h2><div class="minute-data-grid">' + minuteRow("Nombre y apellido", data.first_name + " " + data.last_name) + minuteRow(data.document_type, data.document_number) + minuteRow("CUIL", data.cuil) + minuteRow("Nacimiento", data.birth_date) + minuteRow("Domicilio", data.address) + minuteRow("Localidad / Provincia", data.city_province) + minuteRow("Código postal", data.postal_code) + minuteRow("Estado civil", data.marital_status) + '</div></section><section class="minute-print-section"><h2>Contacto y situación laboral</h2><div class="minute-data-grid">' + minuteRow("Teléfono", data.primary_phone) + minuteRow("Alternativo", data.alternate_phone) + minuteRow("Correo", data.email) + minuteRow("Contacto", data.contact_schedule) + minuteRow("Condición laboral", data.employment_status) + minuteRow("Empresa / actividad", data.employer_name) + minuteRow("Antigüedad", data.employment_seniority + " años") + minuteRow("Ingreso mensual", money(data.monthly_income)) + '</div></section><section class="minute-print-section"><h2>Condiciones comerciales</h2><div class="minute-data-grid three-columns">' + minuteRow("Marca", data.brand_name) + minuteRow("Modelo", data.model_name) + minuteRow("Tipo de plan", data.plan_type) + minuteRow("Precio pactado", money(data.agreed_price)) + minuteRow("Cuotas abonadas", data.installments_paid) + minuteRow("Cuotas a pagar", data.installments_to_pay) + minuteRow("Débito automático", data.automatic_debit ? "Sí" : "No") + minuteRow("Cuota diferida", data.deferred_installment ? "Sí" : "No") + '</div></section><div class="minute-signatures"><div>Firma del cliente</div><div>Aclaración y DNI</div><div>Asesor responsable</div></div><footer class="minute-footer">Documento emitido desde el portal interno de Grupo Sur Automotores · Versión GS-MINUTA-2026-01</footer></article>'; document.getElementById("minutePrint").setAttribute("aria-hidden", "false"); document.body.classList.add("printing-minute"); window.print(); }

  async function markRead(id) { var result = await supabaseClient.from("sales_notifications").update({ read_at: new Date().toISOString() }).eq("id", id); if (!result.error) loadSales(); }
  document.getElementById("newQuoteButton").addEventListener("click", function () { openQuote(); });
  document.getElementById("crmBudgetButton").addEventListener("click", function () { var active = window.grupoSurCRM && window.grupoSurCRM.getActiveLead ? window.grupoSurCRM.getActiveLead() : null; if (active) openQuote(active.id); });
  document.getElementById("quoteModel").addEventListener("change", populateOffers); document.getElementById("quoteOfferType").addEventListener("change", populateOffers); document.getElementById("quoteOffer").addEventListener("change", populateOffers); quoteForm.elements.salePrice.addEventListener("input", calculateQuote); quoteForm.elements.financedAmount.addEventListener("input", calculateQuote); quoteForm.addEventListener("submit", saveQuote);
  document.getElementById("quotesList").addEventListener("click", function (event) { var card = event.target.closest("[data-quote-id]"); if (card && event.target.closest("[data-print-quote]")) { var item = state.quotes.find(function (row) { return row.id === card.dataset.quoteId; }); if (item) printQuote(item); } });
  document.getElementById("refreshSalesButton").addEventListener("click", function () { var button = this; setBusy(button, true, "Actualizando…"); loadSales().finally(function () { setBusy(button, false); }); });
  document.getElementById("salesTrackingList").addEventListener("click", function (event) { var card = event.target.closest("[data-sales-case-id]"); if (card && event.target.closest("[data-open-minute]")) openMinute(card.dataset.salesCaseId); });
  document.getElementById("salesNotifications").addEventListener("click", function (event) { var item = event.target.closest("[data-notification-id]"); if (item && event.target.closest("[data-read-notification]")) markRead(item.dataset.notificationId); }); minuteForm.addEventListener("submit", saveMinute);
  window.grupoSurSales = { loadQuotes: loadQuotes, loadSales: loadSales, openQuote: openQuote, refreshNotifications: loadSales };
  supabaseClient.auth.onAuthStateChange(function (event, session) { if (session && session.user && (event === "SIGNED_IN" || event === "INITIAL_SESSION")) { state.userId = session.user.id; loadSales(); } });
}());
